### ISSUE TITLE
Shell parsable output

### ISSUE THREAD

**Issue by carkar99** [Tyrannican/safir#6]
Hello,

please add a switch to output a shell parsable string like

$ safir get key
key=value

This would make it much more convenient to use safir in shell scripting as safir output could then simply be evaluated
Ty

**Comment by Tyrannican** [comment]
Hey @carkar99 
Sorry for the late reply, this is the next feature that I'll be working on in the near future!

**Comment by Tyrannican** [comment]
This should now be supported as part of Safir v0.8.0
